/* Auto-generated by scripts/write-asset-manifest.ts. Do not edit by hand. */
export const manifest: Record<string, { file: string; css?: string[] }> = {
  "src/client/app.entry.ts": {
    "file": "assets/app-CB7OJ0PH.js",
    "css": [
      "assets/app-D26z903_.css"
    ]
  },
  "src/client/map.entry.ts": {
    "file": "assets/map-Dk39aFmF.js",
    "css": [
      "assets/map-B-YMMjus.css"
    ]
  }
};
