/* Auto-generated by scripts/write-asset-manifest.ts. Do not edit by hand. */
export const manifest: Record<string, { file: string; css?: string[] }> = {
  "_maplibre-gl-B-YMMjus.css": {
    "file": "assets/maplibre-gl-B-YMMjus.css"
  },
  "_maplibre-gl-C-Ekdwb3.js": {
    "file": "assets/maplibre-gl-C-Ekdwb3.js",
    "css": [
      "assets/maplibre-gl-B-YMMjus.css"
    ]
  },
  "src/client/app.entry.ts": {
    "file": "assets/app-BBlGlaVs.js",
    "css": [
      "assets/app-Dbwc8I0M.css"
    ]
  },
  "src/client/map.entry.ts": {
    "file": "assets/map-LE6ZMjEk.js"
  },
  "src/client/pick.entry.ts": {
    "file": "assets/pick-DoTR3x1l.js"
  }
};
