/* Auto-generated by scripts/write-asset-manifest.ts. Do not edit by hand. */
export const manifest: Record<string, { file: string; css?: string[] }> = {
  "_build-style-BCY0Swr6.js": {
    "file": "assets/build-style-BCY0Swr6.js"
  },
  "src/client/app.entry.ts": {
    "file": "assets/app-nbpRhtJh.js",
    "css": [
      "assets/app-BJtMYnXp.css"
    ]
  },
  "src/client/map.entry.ts": {
    "file": "assets/map-DmZJo-lv.js"
  },
  "src/client/pick.entry.ts": {
    "file": "assets/pick-D1Ck2HUv.js"
  }
};
