/**
 * Reads dist/static/.vite/manifest.json (produced by `vite build --mode client`)
 * and writes src/lib/manifest.generated.ts so the Worker bundle can statically
 * resolve hashed asset URLs at runtime.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve("dist/static/.vite/manifest.json");
const TARGET = resolve("src/lib/manifest.generated.ts");

interface ManifestEntry {
  file: string;
  css?: string[];
}

const raw = JSON.parse(readFileSync(SOURCE, "utf8")) as Record<string, ManifestEntry>;
const slim: Record<string, ManifestEntry> = {};
for (const [key, entry] of Object.entries(raw)) {
  slim[key] = entry.css?.length ? { file: entry.file, css: entry.css } : { file: entry.file };
}

const body = `/* Auto-generated by scripts/write-asset-manifest.ts. Do not edit by hand. */
export const manifest: Record<string, { file: string; css?: string[] }> = ${JSON.stringify(
  slim,
  null,
  2,
)};
`;

writeFileSync(TARGET, body);
console.log(`Wrote ${Object.keys(slim).length} manifest entries → ${TARGET}`);
